### ISSUE TITLE
are the latest Scala releases supported? (2.12.12, 2.13.3)

### ISSUE THREAD

**Issue by SethTisue** [DavidGregory084/sbt-tpolecat#26]
the README still lists 2.12.10 and 2.13.1. is it just that the README hasn't been updated? or is the plugin genuinely behind on supporting the latest versions?

**Comment by BalmungSan** [comment]
The latest version seems to work fine with both _(`2.13.2` & `2.12.11`)_ in my own projects, so I guess is just the README being outdated.

**Comment by caoilte** [comment]
I've started seeing complaints about `-Xlint:nullary-override` no longer being a valid flag since I upgraded to 2.13.3.

**Comment by DavidGregory084** [comment]
Sorry @SethTisue, one day I will figure out why I sometimes just don't get notifications about tickets in my own repos 😆 

In this case we were simply not testing the latest patch releases of Scala in this repo. I don't anticipate that there will be  issues because many projects that use sbt-tpolecat & scala steward together hit breaking changes right away and report them here, but I've raised #27 to update the tests.
